---
title: "Hw3"
author: "Lianghui Li"
date: "9/18/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(knitr)
```

## 3.3

### a

We know under gamma prior $G(a,b)$ and $y_i \mid \theta$ follows poisson, the posterior will be $G(a + y,b + n)$, where $y$ is number of the observed, $n$ is number of events.

The posterior distribution for A is $\theta_A \mid y_A$ ~ $gamma(120 + \sum^{10} y_{A_i} = 237, 10 + 10 = 20)$, The posterior distribution for B is $\theta_B \mid y_B$ ~ $gamma(12 + \sum^{10} y_{B_i} = 125, 1 + 13 = 14)$.


```{r}
y_a = c(12,9,12,14,13,13,15,8,15,6)
y_b = c(11,11,10,9,9,8,7,10,6,8,8,9,7)

a_a  = 120
b_a = 10

a_b = 12
b_b = 1
 
a_a_post = a_a + sum(y_a)
b_a_post =  b_a + length(y_a)

a_b_post = a_b + sum(y_b)
b_b_post = b_b + length(y_b)

a_mean_post = a_a_post / b_a_post
b_mean_post = a_b_post / b_b_post

a_var_post = a_a_post / b_a_post^2
b_var_post = a_b_post / b_b_post^2

ci_a_post = qgamma(c(0.025,0.975), a_a_post, b_a_post)
ci_b_post = qgamma(c(0.025,0.975), a_b_post, b_b_post)

df1 = data.frame(t(c(a_mean_post, a_var_post, ci_a_post)))
df1 = rbind(df1, c(b_mean_post, b_var_post, ci_b_post))
colnames(df1) = c("mean", "variance", "2.5%", "97.5%")
rownames(df1) = c("a", "b")

kable(df1)

```

